### PR TITLE
[VBLOCKS-5037] fix: SDP generation with invalid payload types

### LINKED ISSUE #2122: Client is unable to create or apply a local media description in Chrome 137+
We’re encountering a critical issue in Twilio Video when one participant is using Chrome 137+ and the other is using Safari 18.5 (macOS or iOS). The issue occurs in Go rooms and results in a fatal SDP error and one-way audio:

> TwilioError: Client is unable to create or apply a local media description
Failed to parse SessionDescription:
a=rtpmap:96 H264/90000 Duplicate payload type with conflicting codec name or clock rate

🧪 Reproduction Steps
We’ve reproduced this issue using a modified fork of twilio-video-app-react.

📎 Repo: https://github.com/Talb2005/twilio-video-audio-sdp-issue

Modified behavior:

On mute: unpublishTrack() and stop the track

On unmute: createLocalAudioTrack() and publish it again

Steps to reproduce:

1. Join a Go room using Chrome 137+
2. After a few seconds, join the same room from Safari 18.5
3. On Safari, mute the microphone using the unpublish logic
4. Immediately, Chrome logs:
> Uncaught (in promise) TwilioError: Client is unable to create or apply a local media description
5. From that point forward:

- Chrome logs the same error every time it mutes/unmutes
- Audio from Safari is no longer received by Chrome
- Audio from Chrome continues to reach Safari

✅ No further errors appear in either console after the initial failure.

🔁 Summary of Behavior

| Action                      | Result                                        |
|----------------------------|-----------------------------------------------|
| Chrome 137 joins first     | ✅                                             |
| Safari 18.5 joins later    | ✅                                             |
| Safari mutes               | ❌ Triggers SDP error in Chrome               |
| Chrome mutes/unmutes       | ⚠️ Logs error each time                      |
| Chrome hears Safari        | ❌ **No audio received**                      |
| Safari hears Chrome        | ✅ Audio is received normally                 |

🔬 Environment

| Component           | Version / Info                                         |
|---------------------|--------------------------------------------------------|
| Chrome              | 137.0.x (Windows/macOS)                                |
| Safari              | 18.5 (macOS / iOS)                                     |
| Twilio Video SDK    | 2.x.x (unchanged)                                      |
| Room Type           | **Go** (confirmed affected)<br>**Group** (not ruled out) |
| Mute Logic          | `unpublishTrack()` + `createLocalAudioTrack()`         |
| Works Fine With     | `audioTrack.enabled = false/true`                      |

📊 Error Prevalence (in production)

- We’ve seen over 2,500 occurrences across ~1,400 unique users
- Most affected browsers: Chrome 137+, Edge 137+
- Most affected OSs: Windows, macOS

⚠️ Suspected Cause

Chrome 137+ appears to have introduced a regression in SDP negotiation behavior — possibly reusing PT 96 for `H264/90000` with conflicting codec parameters. When the Safari participant mutes using `unpublishTrack()`, Twilio’s returned SDP contains a conflicting codec mapping, which Chrome fails to parse during `setRemoteDescription()`.

> Although the error appears in Chrome, it’s Safari’s audio that fails to reach Chrome — resulting in one-way media failure.

🔗 Possibly Related
#2120 — Similar issue with Chrome 137 and Safari interop during initial connection

🙏 Request
Could the Twilio team:

Confirm whether this is a known regression triggered by Chrome 137+

Recommend any temporary mitigations

Share whether a fix is being planned — either server-side or in the SDK

We’re happy to provide Room SIDs, logs, or live reproduction if helpful. This is actively affecting production sessions on our remote therapy platform.

Thank you!

### PR DESCRIPTION
**Pull request by luisrivas**
### Description
- This PR prevents repeated payload types in the munged SDP section.
- Fixes #2122 

### Before review
* [x] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [x] Ready for review

### CODE REVIEW

**Review by charliesantos — APPROVED** [review]
Great find @luisrivas

File: lib/signaling/v2/peerconnection.js [hunk 1]
```diff
@@ -1745,6 +1745,14 @@ function filterOutMediaStreamIds(sdp) {
  * @returns {boolean}
  */
 function shouldRecycleTransceiver(transceiver, pcv2) {
+  // NOTE(lrivas): Disable transceiver recycling for Safari to prevent
+  // payload type reuse conflicts during track unpublish/republish scenarios
+  // in P2P rooms. See, https://github.com/twilio/twilio-video.js/issues/2122.
+  // This can be revisited once we remove the SDP munging logic for Safari.
+  if (isSafari) {
+    return false;
```
Comment (ramapal) [inline lib/signaling/v2/peerconnection.js]: Does recycling the transceiver cause the PT clash? I can see how previously assigned PTs might get reused unaware of the recycling.

Comment (luisrivas) [reply lib/signaling/v2/peerconnection.js]: No, it does not. It was a red herring, and I'm now addressing the issue differently.

**Comment by luisrivas** [comment]
@charliesantos @ramapal 

While we initially suspected that the browser's native WebRTC was generating malformed SDP, I confirmed that plain JavaScript generates perfectly clean SDP with no duplicate payload types. When our codec‑filtering logic builds its list of payload types (PTs) by iterating over every advertised mapping, it ends up adding the same PT multiple times. That, down the road, produces malformed SDP offers (each PT is only allowed once by the specification). This SDP manipulation may be replaced in the future with a more effective native codec negotiation.

**Comment by charliesantos** [comment]
> @charliesantos @ramapal
> 
> While we initially suspected that the browser's native WebRTC was generating malformed SDP, I confirmed that plain JavaScript generates perfectly clean SDP with no duplicate payload types. When our codec‑filtering logic builds its list of payload types (PTs) by iterating over every advertised mapping, it ends up adding the same PT multiple times. That, down the road, produces malformed SDP offers (each PT is only allowed once by the specification). This SDP manipulation may be replaced in the future with a more effective native codec negotiation.

Understood. We're going to remove this logic soon so it's ok as a fix in the meantime.
